### ISSUE TITLE
Reduce left-side travel required

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-firmware#14] opened 2018-01-09 19:12 UTC
If I understand what I am looking at, our current firmware requires that the user move the carriage 32 stitches to the left of the work before turning around (`#define END_OF_LINE_OFFSET_L 32`) but only 12 stitches to the right (`#define END_OF_LINE_OFFSET_R 12`):
https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/master/settings.h#L92

The additional travel required, and time for that travel, before one hears the end-of-line beep is one of the contributing factors for why AYAB can appear to be significantly slower than knitting with the original hardware. (And, in some cases, has lead to mispatterning, having not gone far enough and waiting for the beep before turning around.)

In testing, we were able to change END_OF_LINE_OFFSET_L down to 12, matching the right-side travel, without any obvious ill effect. If there is a reason _not_ to make this change, I'd like to know what it is.

**Comment by chris007de** [comment] 2018-01-11 20:45
Duplicate of #9

**Closed by chris007de** 2018-01-11 20:45 UTC
Labels: enhancement
